### ISSUE TITLE
Testing: Add tests for `getList`

### ISSUE THREAD

**Issue by igeligel** [kartoffelkraft/email-octopus-ts#101]
## Description

There are currently no tests for the `getList` functionality. Some should be added.

## Libraries to use

- [Jest](https://jestjs.io/docs/getting-started)
- Have a look at `createContact.test.ts` ([Code](https://github.com/kartoffelkraft/email-octopus-ts/blob/main/src/lists/createContact.test.ts)) to see an example how to test

## Files involved

- `src/lists/getList.ts` - File to be tested
- `src/lists/createContact.test.ts`

**Comment by tiago154** [comment]
Hello @igeligel 
I would like to do this task

**Comment by igeligel** [comment]
Hey @tiago154 ,

Feel free to work on this!
