### ISSUE TITLE
Refactoring rename apiGlobalErrorHandler to apiGlobalAxiosErrorHandler

### ISSUE THREAD

**Issue by igeligel** [kartoffelkraft/email-octopus-ts#97]
## Type of Change

- [x] Name variables and functions well
- [ ] Remove magic numbers
- [ ] Extract each step of logic into a function
- [ ] Extract React component
- [ ] Remove duplicate code
- [ ] Other

## Description

We want to replace `axios` with `fetch`. One part of this is replacing the `apiGlobalErrorHandler` but considering we can't just migrate in one with the big bang we need to migrate slowly. For this we need to rename the file and rename the method.

https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API

## Code Before

```tsx
import { handleApiGlobalErrors } from "../handlers/apiGlobalErrorHandler";

// ...
handleApiGlobalErrors(error, errorData);
```

## Code Expected after Refactoring

```tsx
import { handleApiGlobalAxiosErrors } from "../handlers/apiGlobalAxiosErrorHandler";

// ...
handleApiGlobalAxiosErrors (error, errorData);
```

## Files involved

- `handlers/apiGlobalAxiosErrorHandler`
- And all usages

**Comment by Danishkar** [comment]
Can i work on this?

**Comment by igeligel** [comment]
@Danishkar Yes feel free to!
