### ISSUE TITLE
Testing: Add tests for `createList`

### ISSUE THREAD

**Issue by igeligel** [kartoffelkraft/email-octopus-ts#98]
## Description

There are currently no tests for the `createList` functionality. Some should be added.

## Libraries to use

- [Jest](https://jestjs.io/docs/getting-started)
- Have a look at `createContact.test.ts` ([Code](https://github.com/kartoffelkraft/email-octopus-ts/blob/main/src/lists/createContact.test.ts)) to see an example how to test

## Files involved

- `src/lists/createList.ts` - File to be tested
- `src/lists/createContact.test.ts`

**Comment by DiguyaDeveloper** [comment]
Hello, I would like to resolve this issue

**Comment by DiguyaDeveloper** [comment]
Can you assign this issue to me?

**Comment by igeligel** [comment]
Assigned to you! Feel free to start working on this! Thanks for considering to contribute.

**Comment by DiguyaDeveloper** [comment]
Thanks @igeligel, I'm starting at hacktoberfest, can I consider submitting the resolution tomorrow or is there a deadline for signed activities?

**Comment by DiguyaDeveloper** [comment]
This will be my first contribution

**Comment by igeligel** [comment]
There is no deadline of course. Take your time!

**Comment by DiguyaDeveloper** [comment]
@igeligel good night!

With the [pull request](https://github.com/kartoffelkraft/email-octopus-ts/pull/113) I add the solution to the issue, but I have some questions, I don't see the need to test all cases of handleApiGlobalAxiosErrors in the validation of my controller, as handleApiGlobalAxiosErrors must have its isolated test.

The rule for throwing the EmailOctopusError exception is the return of an unknown error, so theoretically only all mapped errors will be caught by the handler and only unmapped errors will return EmailOctopusError, correct?
